set(IDF_TARGET esp32s3)
set(MICROPY_PY_BLUETOOTH 0)
list(APPEND MICROPY_DEF_BOARD MICROPY_PY_BLUETOOTH=0)

set(SDKCONFIG_DEFAULTS
    ${CMAKE_CURRENT_SOURCE_DIR}/boards/sdkconfig.base
    ${MICROPY_BOARD_DIR}/sdkconfig.board
)
