#ifndef MICROPY_HW_BOARD_NAME
#define MICROPY_HW_BOARD_NAME "New Horizons OS ESP32-S3-MINI-1-N8"
#endif

#define MICROPY_HW_MCU_NAME "ESP32-S3"

#define MICROPY_HW_ENABLE_UART_REPL (1)

#define MICROPY_HW_I2C0_SCL (9)
#define MICROPY_HW_I2C0_SDA (8)
